export { WatchLater } from "./watchLater/WatchLater";
export { HomePage } from "./homepage/HomePage";
export { WatchPage } from "./watch/WatchPage";
export { LoginPage } from "./profile-login/LoginPage";
export { Profile } from "./profile-page/Profile";
export { LikedPage } from "./like-page/LikedPage";
export { Library } from "./library/Library";
export { HistoryPage } from "./history/HistoryPage";
export { SignUpPage } from "./signup-page/SignUpPage";